name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  APP_NAME: "service-provider"
  RESOURCE_GROUP: "docker-SC"
  DOCKER_IMAGE: "docker.io/ahmedaladdin0/service-provider:${{ github.sha }}"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker push ${{ env.DOCKER_IMAGE }}

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_IMAGE }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.APP_NAME }}
